# This workflow builds the app, runs ESLint, runs Prettier, checks for TypeScript compilation errors, and runs all tests.
name: Frontend-CI
on: push
jobs:
  build-lint-tsc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run ESLint
        run: pnpm lint
      - name: Run Prettier check
        run: pnpm prettier:check
      - name: Run TypeScript compiler
        run: pnpm tsc --noEmit
      - name: Run tests
        run: pnpm test
